# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  fude_config = debug
  example_config = debug

else ifeq ($(config),release)
  fude_config = release
  example_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := fude example

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

fude:
ifneq (,$(fude_config))
	@echo "==== Building fude ($(fude_config)) ===="
	@${MAKE} --no-print-directory -C build/scripts -f fude.make config=$(fude_config)
endif

example: fude
ifneq (,$(example_config))
	@echo "==== Building example ($(example_config)) ===="
	@${MAKE} --no-print-directory -C build/scripts -f example.make config=$(example_config)
endif

clean:
	@${MAKE} --no-print-directory -C build/scripts -f fude.make clean
	@${MAKE} --no-print-directory -C build/scripts -f example.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   fude"
	@echo "   example"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"